server:
  port: 8888
  context-path: /work
  #热部署
  jsp-servlet:
    init-parameters:
      development: true
#springboot的数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 修改springboot的代理形式 true为cglib
  aop:
    proxy-target-class: true
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  #日志
logging:
  level:
    root: error
    com.baizhi.dao: debug
  pattern:
    console: "[%p]:%m%n"
